### ISSUE TITLE
Session received frame failed: Channel was closed, try reconnect.

### ISSUE THREAD

**Issue by ForteScarlet** [simple-robot/simbot-component-kook#116]
```
2023-10-11T21:42:02.903+08:00 ERROR 3386134 --- [atcher-worker-2] l.f.s.kook.bot.client.jqdlyHK85xe1i5Bo   : Session received frame failed: Channel was closed, try reconnect.

kotlinx.coroutines.channels.ClosedReceiveChannelException: Channel was closed
        at kotlinx.coroutines.channels.Closed.getReceiveException(AbstractChannel.kt:1108) ~[kotlinx-coroutines-core-jvm-1.6.4.jar!/:na]
        at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.resumeReceiveClosed(AbstractChannel.kt:913) ~[kotlinx-coroutines-core-jvm-1.6.4.jar!/:na]
        at kotlinx.coroutines.channels.AbstractChannel.receiveSuspend(AbstractChannel.kt:609) ~[kotlinx-coroutines-core-jvm-1.6.4.jar!/:na]
        at kotlinx.coroutines.channels.AbstractChannel.receive(AbstractChannel.kt:593) ~[kotlinx-coroutines-core-jvm-1.6.4.jar!/:na]
        at love.forte.simbot.kook.internal.KookBotImpl$Receive.invoke(KookBotImpl.kt:551) ~[simbot-component-kook-stdlib-3.0.0.0-alpha.4.jar!/:na]
        at love.forte.simbot.kook.internal.KookBotImpl$StageLoop.invoke(KookBotImpl.kt:706) ~[simbot-component-kook-stdlib-3.0.0.0-alpha.4.jar!/:na]
        at love.forte.simbot.kook.internal.KookBotImpl$StageLoop.run(KookBotImpl.kt:693) ~[simbot-component-kook-stdlib-3.0.0.0-alpha.4.jar!/:na]
        at love.forte.simbot.kook.internal.KookBotImpl$StageLoop$run$1.invokeSuspend(KookBotImpl.kt) ~[simbot-component-kook-stdlib-3.0.0.0-alpha.4.jar!/:na]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.10.jar!/:1.8.10-release-430(1.8.10)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[kotlinx-coroutines-core-jvm-1.6.4.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.4.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.6.4.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.4.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.4.jar!/:na]

```

**Comment by ForteScarlet** [comment]
断线重连似乎还有问题，需要优化

**Comment by ForteScarlet** [comment]
不对，这好像是旧版本的错误

**Comment by ForteScarlet** [comment]
问题似乎仍然存在
