### ISSUE TITLE
无法解析 `SYS_MSG` 类型事件

### ISSUE THREAD

**Issue by ForteScarlet** [simple-robot/simbot-component-kook#58]
在私聊中邀请bot时出现。

```
Session flow on error: Unknown event type property: "SYS_MSG"
love.forte.simbot.kook.event.KookSignalException: Unknown event type property: "SYS_MSG"
        at love.forte.simbot.kook.internal.KookBotImpl$processEvent$3.invokeSuspend(KookBotImpl.kt:540)
        at love.forte.simbot.kook.internal.KookBotImpl$processEvent$3.invoke(KookBotImpl.kt)
        at love.forte.simbot.kook.internal.KookBotImpl$processEvent$3.invoke(KookBotImpl.kt)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
        at love.forte.simbot.kook.internal.KookBotImpl$processEvent$$inlined$mapNotNull$1$2.emit(Emitters.kt:237)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)


```

**Comment by ForteScarlet** [comment]
v4似乎已经被处理（被处理为未知事件），待观察
